[profile.default]
solc = "/opt/homebrew/bin/solc"
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.0'
remappings = [
    "openzeppelin/=lib/openzeppelin-contracts/",
    "abdk-libraries/=lib/abdk-libraries-solidity/"
]

viaIR = true
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 100





# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
